### ISSUE TITLE
Create a new background task to update db

### ISSUE THREAD

**Issue by javaguirre** [javaguirre/gramophone#6]
I think it should be better to have a background task, the update_db view actually it's just for test, so it should be removed and we could just add a button in the app to update db via AJAX.

**Comment by dbrgn** [comment]
I don't think it should be a cron-like background task, it should rather be triggered by an action (e.g. visiting any site).

Maybe we can create a very fast way to detect changes in the music folder? The explore module needs big performance improvements anyways...

The update_db is good for initial loading of the music library, because a big library can take minutes to process.

**Comment by javaguirre** [comment]
I think you are right! We could keep it that way and create a faster way of update the db, would you like to work in it?

**Comment by dbrgn** [comment]
Yeah, I'll refactor explore.py sometime.

**Comment by dbrgn** [comment]
Has this been fixed, or why did you close this issue?

**Comment by javaguirre** [comment]
I closed it because we agreed not to have a background task, and the speed up explore.py is in the issue #8 don't you think? This was duplicated.

**Comment by dbrgn** [comment]
Ah, yeah, sorry :)
